#  the script takes an orthogroup fasta file generated by orthofinder as input. The original script 
#  would generate this file from a csv list, but since it is already generated by orthofinder
#  I will skip this step and go immediately to the alignment.

#  The original script offers different alignment software options, but I will only implement clustal-OMEGA.

##	INPUT
#	(+)An orthogroup multifasta file generated by orthofinder. (only use orthogroups exclusively
#       consisting of 1-to-1 orthologs!)
#	(+)Corresponding DNA and Protein sequences for each ortholog, in FASTA format. 
#       If a directory is given then the script will assume it contains complete cds fastas and extract the required sequences by sequence header itself

##	OUTPUT
#	Up to four files will be generated for each desired ID:
#	(+)<orthogroup_ID>.fa_extracted_cds.fna	| A multiple-sequence FASTA file of the Nucleotide orthologs. Not aligned.
#	(+)orthogroup.prot_aln.fasta			| An alignment file of the protein orthologs, FASTA format.
#	(+)orthogroup.pal2nal.paml		    	| A codon-based nucleotide ortholog alignment, for use with PAML
#	(+)[2YN|2NG].dNdS   	    	    	| pairwise dN/dS values calculated by yn00 or codeml respectively

##  REQUIREMENTS:
#   (+) stuff on uppmax:
#       module load bioinfo-tools clustalo/1.2.4 biopython/1.80-py3.10.8 paml/4.10.7
#       (+) emboss          | to translate the nucleotide sequences into proteinfasta with transeq, on uppmax it's emboss/6.6.0
#       (+) BioPython       | (The original script uses BioPerl since it's in perl), can be loaded as uppmax module
#       (+) CLUSTAL-Omega   | (For multiple-sequence alignments), can be loaded as uppmax module
#   (+) stuff not on uppmax:
#       (+) pal2nal         | (not available on uppmax, get from github and set binary path with command line flag)
#                           | /proj/naiss2023-6-65/Lila/beetle_genomes/pal2nal.v14/pal2nal.pl
#       (+) MKado           | (installed with pip in venv)
#                           | source /proj/coleoptera-genomics-2025/snic2021-6-30/Milena/python_venvs/mkado_venv/bin/activate

#	For USAGE please run without any options or specifying flag -h or --help



import argparse
from Bio import SeqIO, AlignIO
from Bio.SeqRecord import SeqRecord
import os
import subprocess
import re
import time
import scipy


def parse_args():
    # Create the parser
    program_description = """
A script to calculate the MKtest between two sequences in a fasta file and a population-level vcf for one species.
The individual steps consist of:
(1) make a proteinfasta by translating the cds fasta
(2) make a codon-based multi-sequence alignment 
(3) project the vcf onto the alignment to also get polymorphism data
(4) run MKtest
"""
    parser = argparse.ArgumentParser(description=program_description)

    # Add the arguments
    parser.add_argument('--cds', required=True, help="coding sequence (aminoacid) multifasta containing the two sequences between which you would like to calculate the dNdS ratio")
    parser.add_argument('--vcf', required=True, help="VCF of the polymorphism data")
    parser.add_argument('-o', '--outdir', type=str, help='Directory where the output_file is stored, default: working directory, make new dir named like filename from cds input (truncated at last point to remove file extension)')
    
    parser.add_argument('--pal2nalbin', type=str, help="Absolute path to an executeable to run pal2nal, default: ./pal2nal.pl")
    parser.add_argument('--pal2naloptions', type=str, help="command line options for pal2nal, default: -output paml -nogap -nomismatch")
    
    parser.add_argument('--clustalbin', type=str, help="path to the clustal-omega executeable if it is not default clustalo. not necessary if the uppmax module is loaded with: module load clustalo/1.2.4")
    parser.add_argument('--alnoptions', type=str, help="optional alignment options, empty by default")

    parser.add_argument('--MKado_venv', type=str, help="path to MKado python venv so that it can be activated with source venv_path/bin/activate")
    parser.add_argument('--MKado_build_polymorphism_path', type=str, help="path to MKado python script build_mk_dataset.py")

    parser.add_argument('--verbose', action='store_true', help="enable verbose mode")
    parser.add_argument('--overwrite', action='store_true', help="overwrite existing output files with default names from previous runs")

    # Parse the arguments
    args = parser.parse_args()

    # set default values for non-obligatory arguments
    if not args.outdir:
        args.outdir = args.cds.split("/")[-1].split(".")[0]+"_dNdS"
        # print(f"no output directory provided, default directory created: {args.outdir}")
    if not args.pal2nalbin:
        args.pal2nalbin = "./pal2nal.pl" # assumes pal2nal is in the current directory
    if not args.pal2naloptions:
        args.pal2naloptions = "-output clustal -nogap -nomismatch" # Originally: -output clustal -nogap -nomismatch"  
    if not args.alnoptions:
        args.alnoptions = ""
    if not args.clustalbin:
        args.clustalbin = "clustalo"
    
    if args.outdir[-1]!="/": # if outdir does not include a trailing "/", add it
        args.outdir=args.outdir+"/"

    return args



def make_cds_fasta(proteinfasta, cds_list, verbose):

    nucleotide_fasta = []
    record_found = False

    print(f"generating CDS fasta file from {proteinfasta}")

    start_time = time.time()
    # go through all protein names in the proteinfasta
    for OG_record in SeqIO.parse(proteinfasta, "fasta"):
        record_found=False

        # remove the trailing "_1" that the orthofinder protein ID names have
        if OG_record.id[-2:] =="_1":
            OG_record.id = OG_record.id[:-2]
        if verbose:
                print(f"\tcurrently seqrching: {OG_record.id}")
    
        # find which protein header matches the current OG_record.id
        for species in cds_list:
            if verbose:
                species_print = species.split("/")[-1]
                print(f"\t\tcurrently reading: {species_print}")
            for species_cds in SeqIO.parse(species, "fasta"):

                # orthofinder replaces "|" with "_", so I have to replace it here too or I won't find matches 
                if "|" in species_cds.id:
                    header = species_cds.id
                    header = header.replace("|", "_")
                    species_cds.id = header

                # find matching species_cds.id in complete nucleotide cds files
                if species_cds.id in OG_record.id or OG_record.id in species_cds.id:
                    # print(species_cds.id)
                    species_cds.id = OG_record.id.split(" ")[0]
                    nucleotide_fasta.append(species_cds)
                    record_found=True
                    break # don't continue if a match is found. It seems like it works pretty well with the unique gene names, so breaking here to cut down on runtime instead of including a warning for double-matches seems worth it
            if record_found==True:
                if verbose:
                    print(f"\t\tfound! {species_cds.id}")
                break
                # break 
        if record_found==False:
            print(f'WARNING: no matching cds record found for protein record {OG_record.id} in orthogroup file {proteinfasta}.')
    
    end_time = time.time()
    passed_time = end_time - start_time
    if verbose:
        print(f"making the nucleotide fasta file took {passed_time:.2f} seconds, or {passed_time/60.0:.2f} minutes")
    return(nucleotide_fasta)



def is_file_non_empty(file_path):
    # Check if the file exists
    if os.path.isfile(file_path):
        # Get the size of the file
        if os.path.getsize(file_path) > 0:
            return True
    return False


def make_proteinfasta(cds_fasta_path, outdir, auto_modify_headers = False):
    """
    make a proteinfasta file in the output directory that is translated from cds_Fasta_path
    later for phylip sequential headers get truncated to 10 bp, so when auto_modify_headers is on, 
    check if the first 10 characters are identical add a prefix to the ID to make sure this does not cause problems later
    """
    prot_name = f"{outdir}protein_sequences.faa"
    prot_records = []

    modify_headers = False
    if auto_modify_headers:
        headers = []
        count_seqs = 0
        for seq_record in SeqIO.parse(cds_fasta_path, "fasta"):
            headers.append(seq_record.id[:10])
            count_seqs+=1
        # print(headers)
        unique_headers = len(list(set(headers)))
        if unique_headers != count_seqs:
            modify_headers = True

    if modify_headers:
        if verbose:
            print(f"non-unique headers detected! {headers} --> add prefix")
        nuc_records = []
    
    for i, seq_record in enumerate(SeqIO.parse(cds_fasta_path, "fasta")):
        prot_record = SeqRecord("")
        # to avoid some weird in-place editing of the nucleotide SeqRecords I am doing it this way
        try:
            nuc_seq = seq_record.seq
            prot_record.seq =nuc_seq.translate(cds=True)
            prot_record.id = seq_record.id
            # print(f"nucleotide: {nuc_seq}")
            # print(f"protein: {prot_record.seq}")
        except Exception as e:
            os._exit(f"no translation possible: {e}")
            raise RuntimeError(f"error in sequence translation: {e}")
        
        if modify_headers:
            prot_record_name = prot_record.id.replace(">", "")
            seq_record_name = seq_record.id.replace(">", "")
            prot_record.id = f">{i}_{prot_record_name}"
            seq_record.id = f">{i}_{seq_record_name}"
            nuc_records.append(seq_record)
            # print(nuc_records)
        prot_records.append(prot_record)
        # print(prot_records)
    try:
        SeqIO.write(prot_records, prot_name, "fasta")
    except Exception as e:
        wd = os.getcwd()
        raise RuntimeError(f"writing to file did not work:\n{e}\n--> failing to write {prot_name} in {wd}")
    if modify_headers:
        SeqIO.write(nuc_records, cds_fasta_path, "fasta")
    return prot_name



if __name__ == '__main__':
    
    ### define variables from command line input

    args=parse_args()
    outdir_path = args.outdir
    cds_path = args.cds

    clustal_bin = args.clustalbin
    pal2nal_bin = args.pal2nalbin
    pal2nal_options = args.pal2naloptions
    aln_options = args.alnoptions
    verbose = args.verbose
    overwrite = args.overwrite
    
    if verbose:
        print()
    
    topdir = os.getcwd() # working directory above all the output directories
    
    if verbose:
        print(f"\n====================== {outdir_path} ======================")
        # take care of output directory

        try:
            os.makedirs(outdir_path)
            print(f"The specified output directory is created at: {outdir_path}")
        except Exception as e:
            if os.path.exists(outdir_path):
                if overwrite:
                    print(f"The output directory {outdir_path} already exists and overwrite mode is enabled, therefore existing output files are overwritten")
                else:
                    print(f"The output directory {outdir_path} already exists, but overwrite mode is disabled so existing outfiles are used")

            else:
                wd = os.getcwd()
                print(f"{outdir_path} could not be created in {wd}.\nERROR:\n{e}")

        print()
    else:
        try:
            os.makedirs(outdir_path)
        except Exception as e:
            if os.path.exists(outdir_path):
                if overwrite:
                    print(f"The output directory {outdir_path} already exists and overwrite mode is enabled, therefore existing output files are overwritten")
                else:
                    print(f"The output directory {outdir_path} already exists, but overwrite mode is disabled so existing outfiles are used")
            else:
                wd = os.getcwd()
                print(f"{outdir_path} could not be created in {wd}.\nERROR:\n{e}")

    
    ############################
    ### make multifasta file ###
    ############################

    # check if the cds input is a directory (contains cds fasta complete for all species of interest)
    # or a file (cds multifasta directly corresponding to the proteinfasta orthogroup input file)

    if os.path.isfile(cds_path) and os.path.getsize(cds_path) > 0:
        if verbose:
            print(f"'{cds_path}' found!")
        # list and print files in directory
    elif os.path.isfile(cds_path):
        raise RuntimeError(f"'{cds_path}' not found!")
    elif os.path.getsize(cds_path) == 0:
        raise RuntimeError(f"'{cds_path}' is empty!")


    ###########################################
    ######## translate to proteinfasta ########
    ###########################################

    prot_path = make_proteinfasta(cds_path, outdir_path, auto_modify_headers = True)
    if verbose:
        print(f"protein sequences translated: {prot_path}")

    
    ###########################################
    ### do the alignment with clustal-omega ###
    ###########################################

    clustal_outfile = f"{outdir_path}prot_aln.fasta"

    # check if an alignment file exists from a previous run
    if not os.path.exists(clustal_outfile) or overwrite:
        if verbose:
            print("\n *  starting clustal-OMEGA:\n")
            if overwrite:
                print(f"overwrite mode enabled --> overwriting existing file {clustal_outfile}")
    
        clustal_omega_command = f"{clustal_bin} {aln_options} -i {prot_path} -o {clustal_outfile}"
        if overwrite:
            clustal_omega_command = f"{clustal_bin} {aln_options} -i {prot_path} -o {clustal_outfile} --force"

        start_time = time.time()
        if verbose:
            print("command: "+clustal_omega_command)
        end_time = time.time()
        if verbose:
            passed_time = end_time - start_time
            if verbose:
                print(f"making the alignment took {passed_time:.2f} seconds, or {passed_time/60.0:.2f} minutes")
                
        result = subprocess.run(clustal_omega_command, shell = True, capture_output=True, text=True)
        # Check if the command was successful
        if result.returncode == 0:
            if verbose:
                print("clustal-OMEGA ran successfully.")
                print(result.stdout)
        elif is_file_non_empty(clustal_outfile)==False:
            raise RuntimeError(f"clustal-OMEGA outfile: {clustal_outfile} is empty")
        else:
            wd = os.getcwd()
            filesize = os.path.getsize(clustal_outfile)
            raise RuntimeError(f"clustal-OMEGA failed in directory {wd}")

    else:
        if verbose:
            print(f"{clustal_outfile} exists already, using existing file for next steps.")


    #####################################
    ############ run pal2nal ############
    #####################################

    pal2nal_alignment = f"{clustal_outfile}.paml"
    pal2nal_command = f"{pal2nal_bin} {clustal_outfile} {cds_path} {pal2nal_options} > {pal2nal_alignment}"

    if verbose:
        print(" *  running pal2nal (codon based alignment)\n")
        print("command: "+pal2nal_command)
    result = subprocess.run(pal2nal_command, shell = True, capture_output=True, text=True)
    # Check if the command was successful
    if result.returncode == 0:
        if verbose:
            print(f"pal2nal ran successfully")
    else:
        raise RuntimeError(f"pal2nal failed!\n{result.stderr}")
    if os.path.getsize(pal2nal_alignment) == 0:
        raise RuntimeError(f"pal2nal failed, {pal2nal_alignment} is empty")

    # Read the Clustal file
    alignment = AlignIO.read(f"{pal2nal_alignment}", "clustal")

    # Write the alignment in FASTA
    AlignIO.write(alignment, f"{pal2nal_alignment}", "fasta")

    if verbose:
        print(f"done, adjusted spacing in {pal2nal_alignment}")
        print()
    



